# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: One Crow
email: pconerly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning Go, one blog post at a time.
baseurl: "/onecrow" # the subpath of your site, e.g. /blog
url: "http://pconerly.github.io" # the base hostname & protocol for your site
github_username:  pconerly

# Build settings
markdown: kramdown
